version: '3.8'

services:
  app:
    container_name: ci-mf-sandbox
    build:
      context: .
      target: ci-mf-sandbox
    ports:
      - published: ${APP_PORT:-80}
        target: 3000
    networks:
      - prodnet

networks:
  prodnet: