version: 2.1

orbs:
  node: circleci/node@4.1
  aws-cli: circleci/aws-cli@1.3.0
  aws-code-deploy: circleci/aws-code-deploy@1.0.1
  aws-ecr: circleci/aws-ecr@6.13.0

jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test

  build-and-push:
    docker:
      - image: circleci/python:3.7.1
        user: root
    steps:
      - checkout
      - setup_remote_docker
      - aws-ecr/build-image:
          repo: ci-mf-sandbox
          tag: latest-v0.1.${CIRCLE_BUILD_NUM}
      - aws-cli/install
      - aws-ecr/ecr-login
      - aws-ecr/push-image:
          repo: ci-mf-sandbox
          tag: latest-v0.1.${CIRCLE_BUILD_NUM}

workflows:
  build_test_deploy:
    jobs:
      - test
 
      - build-and-push:
          requires:
            - test
