version: 2.1

orbs:
  node: circleci/node@4.1

references:
  node_defaults: &node_defaults
    working_directory: ~/repo
    machine:
      image: ubuntu-2004:202107-02

jobs:
  checkout_code:
    <<: *node_defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  install_dependencies:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm i
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules

  run_unit_tests:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm run test

  run_e2e_tests:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm run test:e2e

workflows:
  build_test_deploy:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - run_unit_tests:
          requires:
            - install_dependencies
      - run_e2e_tests:
          requires:
            - install_dependencies
