version: 2.1

orbs:
  node: circleci/node@4.1
  aws-cli: circleci/aws-cli@1.3.0
  aws-code-deploy: circleci/aws-code-deploy@1.0.1
  aws-ecr: circleci/aws-ecr@6.13.0

jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test

  build-and-push:
    docker:
      - image: circleci/python:3.7.1
        user: root
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - setup_remote_docker
      - aws-ecr/build-image:
          repo: calluna-ecr-ci-mf-sandbox-staging
          tag: latest-v0.1.${CIRCLE_BUILD_NUM}
      - aws-cli/install
      - aws-ecr/ecr-login
      - aws-ecr/push-image:
          repo: calluna-ecr-ci-mf-sandbox-staging
          tag: latest-v0.1.${CIRCLE_BUILD_NUM}

  code-deploy:
    executor: aws-cli/default
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Configure deployment
          command: |
            echo IMAGE=${AWS_ECR_ACCOUNT_URL}/calluna-ecr-ci-mf-sandbox-staging:latest-v0.1.${CIRCLE_BUILD_NUM} >> .env
      - aws-cli/setup
      - aws-code-deploy/push-bundle:
          application-name: calluna-ci-mf-sandbox-staging-main_app
          bundle-bucket: calluna-bucket-ci-mf-sandbox-staging
          bundle-key: codedeploy/${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BUILD_NUM}
      - aws-code-deploy/deploy-bundle:
          application-name: calluna-ci-mf-sandbox-staging-main_app
          bundle-bucket: calluna-bucket-ci-mf-sandbox-staging
          bundle-key: codedeploy/${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BUILD_NUM}
          deployment-group: calluna-ci-mf-sandbox-staging-main_app-group

workflows:
  build_test_deploy:
    jobs:
      - test
      - build-and-push:
          requires:
            - test
      - code-deploy:
          requires:
            - build-and-push
