version: 2.1
orbs:
  node: circleci/node@4.1
  aws-ecr: circleci/aws-ecr@6.15.0
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
workflows:
  test-and-deploy:
    jobs:
      - test
      - aws-ecr/build-and-push-image:
        repo: ci-mf-sandbox
        tag: "latest,v0.1.${CIRCLE_BUILD_NUM}"
        dockerfile: Dockerfile
        path: .
        requires:
          - test
