version: 2.1

orbs:
  node: circleci/node@4.1

references:
  node_defaults: &node_defaults
    working_directory: ~/repo
    docker:
      - image: cimg/node:14.15.4

jobs:
  checkout_code:
    <<: *node_defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  install_dependencies:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm i
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules
  run_e2e_tests:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker
      - run: npm i
      - run: npm run test:e2e

workflows:
  build_test_deploy:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - run_e2e_tests:
          requires:
            - install_dependencies
